--- 
abstract: A co-operative multithreaded server using Coro
author: 
  - Alex Vandiver <alexmv@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Server-Coro
no_index: 
  directory: 
    - inc
    - t
requires: 
  Coro: 0
  EV: 0
  Net::Server: 0
version: 0.4
