---
abstract: 'A co-operative multithreaded server using Coro'
author:
  - 'Alex Vandiver <alexmv@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Server-Coro
no_index:
  directory:
    - inc
recommends:
  Net::SSLeay: 0
requires:
  Coro: 0
  EV: 0
  Net::Server: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 1.2
